### ISSUE TITLE
Define the evaluation

### ISSUE THREAD

**Issue by sirspock** [KnowledgeCaptureAndDiscovery/OBA#47]
We need to define the evaluation.

What the aspects?

**Comment by dgarijo** [comment]
We are not going to formally evaluate the system. We are going to showcase that the system is appropriate in different scenarios. A qualitative evaluations.
Scenario 1: 1 Simple ontology (provenance). We want to do GET queries based on templates. This shows that we can support simple open api specs. [to do]
Scenario 2: 1 big ontology (DBPedia). We produce the spec. We show that we can filter some concepts with OBA. [done] This shows that big ontologies are not an issue, and that we can filter concepts. It would be nice to show here the other tool you showed me for APIs instead of swagger, which is slow when the page is big.
Scenario 3: Ontology network: we have multiple ontologies. OBA supports it. Example with model catalog [done]
Scenario 4: We have a KG where we want to do POST/PUT. Example with model catalog. [done] Here we show that we can do post and put, and there is validation.

**Comment by dgarijo** [comment]
Scenario 5 (after takling to @khider ): In the Linked Earth Wiki they had to do these horrible queries: https://github.com/LinkedEarth/Queries/blob/master/Querying%20the%20LinkedEarth%20Wiki.ipynb
Can we create a couple of custom queries that show how to retrieve data easily? There is an ontology as well, but the URIs may not correspond very well. This is an exciting case

**Comment by dgarijo** [comment]
In the end, we will have 3 main use cases: DBPedia (full); DBPedia (filter); OKGSoft.
